# users-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: users-secrets
  namespace: banking-operations
  labels:
    app: users-service
type: Opaque
data:
  DB_PASSWORD: "YWNjb3VudDEyMw=="
  JWT_SECRET_KEY: "c3VwZXItc2VjcmV0LWtleS1wYXJhLWp3dA=="
  RABBITMQ_PASSWORD: "cmFiYml0MTIz"