apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins-cicd
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      name: ui
    - port: 50000
      targetPort: 50000
      name: agent
  selector:
    app: jenkins-server