# user-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: banking-operations
  labels:
    app: users-service
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "bank_db"
  JWT_ALGORITHM: "HS256"
  ENVIRONMENT: "production"
  DOCKER_MODE: "true"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "admin"